language: perl
sudo: false

perl:
- '5.8'
- '5.10'
- '5.12'
- '5.14'
- '5.16'
- '5.18'
- '5.20'
- '5.22'
- '5.24'
- '5.26'

notifications:
  email: false
  slack:
    secure: QVl2vGjyn/lBkUG+1Uim+MmpWgGZhZ5ufwMcV0/czuaaarFnk+qqbBO2qCuKvkcs8W/N+hVuuF1EzFG0CzIs46g1oTSDrUjXgxp+YYN6qB7QlNEs1I+PamQfkGUnPqLOvxtp7Aus18E/2IVVgee4SEKiimLxC9PxwIrz16bcS8rHR2KbZLjQeI1QaPAH5pwbVa1wP3MEilIKmGzYOfIrWDvTIAkyuonptSyrxZI6yavTbmSP51U5U30sYt8aTO+7Hc8JAowk/cjojVnk7yfJHD4s9RYTJurgYAxD5Kny6PoZC8pFT1GVqgR7R9LOJ1Wn0jHHbkIM3P1XoQl3CSxjCpmj8ITtxf9k6V2CfjyJofcpEnxcmZgz/ltZ5wqo28jLzYdqzGLFeufL3OqIbumVNE8MFvNAZWDuNSy4nuwfe3PH9p24L60toxC9w/V9iQp7fU3JCW7cicYB17HEQGfvTMTE2vBaArUqhnANwjgeoCW6FfZ6ravqufXidKyQX8Lwpplnnphc+ud1IWEd8VNZgrodv4jTpaSZJ30V244/zvkSEV1ro3Xfwqmcl0iN8ZIEVbSBKNPsEM/A/lKrX0AiFUdBZ8XngEyE09ChGQC+xQJENTIroc220viPDPjHKSPFH2Pd5evlFZRdBm7/mf5Z6qWDLWy6vZsh8reTb0k2VyM=
