language: perl

sudo: false

perl:
- '5.8'
- '5.10'
- '5.12'
- '5.14'
- '5.16'
- '5.18'
- '5.20'
- '5.22'
- '5.24'
- '5.26'

notifications:
  email: false
  slack:
    secure: X1KBQCrsrWcuaw4oDM+Sq4Q8kyZUhL4DY6l9uAHSAEE1aAljOlHlXHPtiXLS59lBzm0kFylistxpNz8vleZAEBhfE65MQFmxBh/BssHC0gKvgV4VtH9yC9GRTmb8F8iE1jmtwfaC+Uyn0dN0PKnOSQpY1PdrKtgsM3IQwMMsdl+T+aVqgDGU/uX0E94jECsgxekcv8+KZ57Swh2xspg2BUMM+dQXxPJ91hTHZqC58+pl+szuKCcbv3Rv0p8cmu+kUrHe09eGqm8ZNR5GcVWfZyQrAoNcVTb0/5vf//e414FwWP3nUon7tIz83rDXpxKl1yP/KgDfUXU6T2gcecE6N0edsAJaw9bEBANzYmpa53cIZ2JwdlkH2M7uPbn74PMtUlzfd/3zr+WLAfsO++jlQdNWYxr+OBVNPB1w8/SxVo/kwr5+7A0v2GG+YKm/rMzhO2AzMFvm8awO0KMYOuaVZVA7pdAwXikQMAOAa0wSnE31WDLk14shmAnzIBck5MnygL1jPstLBYHcC1MYyHoP6AzxduX8UUIBSK0GTma1HFH2mWD2FwPyplquUXaVsrNy7BLxzCrqlRQUUBg8F5Idry+k2kbRSA/ncmKj6klBBJDqwpcGz1VZ2i0RBdRMYZS7lVJWKYc5GWAwAQ056NF+6m31jtTa1UU42YJUoFlbxvY=
