language: perl
sudo: false
perl:
- '5.8'
- '5.10'
- '5.12'
- '5.14'
- '5.16'
- '5.18'
- '5.20'
- '5.22'
- '5.24'
- '5.26'
notifications:
  email: false
  slack:
    secure: KHDSowLwJrzj4Bc4pRONXWVI+PQpCJXD/u/pZRYyKF0XtxTqxMctYGIIEKtXtxHqkX4b7/7bDzqbU5S5SYCMM8wxw93XatHUJhIwVaSHxGizbwr97l0cSLpJDP+ItnRTAup5gV5oBGhD86j+mJXwutXrrhy53UqOBjj14mZihKlfTrN0w8Wd5v918+rx6kmjQfremrrd8j3tkjwc3fYMlau7BcPoDlpuIbxUjAFsw9X2Gdf4BxE9+iShaoseBRZaen6fO9p7mmoaicUAObgtNb6SM7P8oQ/JciBPDKsCRZ5dyrYx4qOZWBD/F82gb+DGNaXy8h2S8QivaZd2vVEN8nH2i1mDIkBVaPswc1FOtk0n85PeKcM5Dk/6bhkvH3yN+uGOTvnI5YImDrQxD23Yau5tY+0qVDAa298d/lgOaairBcci8LWJO6/9IUFBgp5o2JtrC8tLulG/8V781WPZ0sNP3mlQq2XGfUyyWjE6R/ahO2cF9O17ekstWs7lnDdTXO8Ah3/2ptX5Q8Vsjr6SxBi3sGjCWKEbVOk5BTjSx5ICyNVkyiaFMR2/UHyHGb68KA1pNovMBSeOtWBYIgHN+OGAL/nk1Df7NBRtNArabbJaLgGNueNbZYNXqV1fdkQjKwgWrewhvp4rkwJw7sKNHeCnVrkHmn1QfVkgJHro6vA=
