language: perl
sudo: false

perl:
- '5.8'
- '5.10'
- '5.12'
- '5.14'
- '5.16'
- '5.18'
- '5.20'
- '5.22'
- '5.24'
- '5.26'

notifications:
    email: false
    slack:
        secure: HJK1HNP7+D3xz1XJrw2rEpge1/FWZstfQTRl6E5MjKtdYwUC9xfDhSCN07MKd7yiQjS525bBMMnsvmS1BPMtx3orh5v4v/Kf0jpt4dLWt0M5iW4+tqE6p09M5k9aub9xd39O39luKq9QANcEGsBNifZCiU7IQGbxCX68WtJYGg1D1I9Td720CdzsiOTlcEIXX4YaSqQdD0iYrYaLz/neCmt4qswBr2eTmLrOpSOWJdYMCK9JIo4yTeeDtc1SwHsZ3s5/Tv91LFVPLzkOXRugfvoiak5uctlwTfHRYYVNGQu/J4UbDr0OA0DBGZ131CQZv89Rngft5szgZBZvkDSj4Cfcoha1DoBFeAiQ0yoTlGhx+o5HybG54Y8fQNbn7+ZS9eNe5eZP8dWM7Y7wbRCTY5/JS4wJXkHpC2i9gau0gvjuAZQF8T3GWyiKcnsrN67NdZIVm7m6KEIB9z1vIVfGx4Fd898YbCMFKhOseQu+3cCEKySk3OWaDYCw2GWBv1cMtmukAjGUJNvcyVkwbonb4M88j5SuKyh2bSPsnDbFtUbmo/2WYX79hfKdfRhlBGh9PfBZtqrMjB0v3DMa74CwkNOLlSA36hUKAn6RDGfJpf92TCfV0sE17b/VxXBjCv/CoD8FbYgRf8SgxXq2zQ53AWsM3LqDfIAxAIU4VBnvkH8=
