language: perl
sudo: false

perl:
- '5.8'
- '5.10'
- '5.12'
- '5.14'
- '5.16'
- '5.18'
- '5.20'
- '5.22'
- '5.24'
- '5.26'

notifications:
  email: false
  slack:
    secure: dmYaNte46RvXxLsNAQC7WMm8o7tUK08pGDdOi7HT/4EJQmcMbJq3Wl5oBfxEhMivm1niCGZGobevB7ZTi9cytHU0tnD0Ysgi8ITRm5Hqgl/x1LdnGOlF8jfIir+6zcrWRGl5CqPGv/boWjoBbUA7knYzUXSX6Edtf+IMNHmodKpykpMdaT+0Uyr67gNPUllY3tTiqxz2S7Lu1JZuCQhG5U1F3e4aixwQTrNZAz4ECJiomeBhGCH/qwHwqmsyGlEWq48sZ95JzUBV8h00yHi2BuDTOYoybJFylKKFFDIF2xhsArMskBF2g4phjQ6CO9TAwjbCKxdWPrLY1gFZv/jUIDFp9i2dWeLZESGa3Eagbo52n1lG1Dn7lsXU3mdCgFljqUROcv28LEpP/PRZI5sysAgjrihOkYGTg08LXyWv0DyPPYqu65xy/0DLHTS9I3GesyLGL5lmHRhkOr0j0bojqYJWbNDmDpemC8Hcuv2nEC+uwuZZFumX9mpzcUcBkWmCPhdmb9uMh6lWd7JxSdT5E4bPeWwQnOCVMArLMso0YAMgD66tX/9ws3+6NXVrtIo692cS6eMFtr/2/rmI6SaGBtUDc2o5nmKWj76uaPhFahYUNlmf5rLaU1QAk7j58Zj7+YWfbbyciES6evJ7ttHe4VUNfm7PzzNyIp7a3urh3lc=
